---
- hosts: similarity_workers
  remote_user: petuomin
  tasks:
  - name: stop similarity worker nodes (killall node processes)
    shell: killall node
    ignore_errors: yes
  - name: start/restart similarity nodes
    shell: nohup node melinda_deduplication/dep/straw/similarity_workers.js &
